apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubeflow/model-registry/manifests/kustomize/overlays/db?ref=v0.2.16

patchesStrategicMerge:
  - mysql-patch.yaml