apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry-db
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.39
          args:
            - --default-authentication-plugin=mysql_native_password
          securityContext:
            capabilities:
              add:
                - SYS_NICE