apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry-mysql
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: mysql
        securityContext:
          capabilities:
            add:
            - SYS_NICE