FROM spark:3.5.5-java17-python3

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/app \
    PATH="/opt/venv/bin:$PATH"

USER root

WORKDIR $APP_HOME

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-venv gcc g++ python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && python3 -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip

COPY requirements-linux.txt .

RUN /opt/venv/bin/pip install -r requirements-linux.txt \
    && rm requirements-linux.txt \
    && mkdir -p $APP_HOME/feature_repo/output/ \
    && chgrp -R 0 $APP_HOME/feature_repo \
    && chmod -R g+w $APP_HOME/feature_repo \
    && mkdir -p $APP_HOME/.ivy2 \
    && chgrp -R 0 $APP_HOME/.ivy2 \
    && chmod -R g+w $APP_HOME/.ivy2

USER spark
