FROM spark:3.5.5-java17-python3

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/app \
    PATH="/opt/venv/bin:$PATH" \
    MINIO_ENDPOINT="http://minio-service:9000" \
    MINIO_ACCESS_KEY="minio" \
    MINIO_SECRET_KEY="minio123" \
    MINIO_BUCKET="mlpipeline"

USER root

WORKDIR $APP_HOME

RUN apt-get update
RUN apt-get install -y --no-install-recommends python3-venv gcc g++ python3-dev
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/pip install --upgrade pip

COPY requirements-linux.txt .

RUN /opt/venv/bin/pip install -r requirements-linux.txt
RUN rm requirements-linux.txt

RUN mkdir -p $APP_HOME/feature_repo/output/
RUN chown -R spark:spark $APP_HOME/feature_repo

RUN mkdir $APP_HOME/.ivy2
RUN chown -R spark:spark $APP_HOME/.ivy2

USER spark
