apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: fraud-detection
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs:
      - get
      - list
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs:
      - create
      - get
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups: [ "" ]
    resources: [ "services", "endpoints", "events", "secrets", "persistentvolumeclaims" ]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups: [ "sparkoperator.k8s.io" ]
    resources:
      - sparkapplications
      - sparkapplications/status
      - scheduledsparkapplications
      - scheduledsparkapplications/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
