apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: fraud-detection
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: fraud-detection
  - kind: ServiceAccount
    name: pipeline-runner-sample
    namespace: fraud-detection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
