FROM spark:3.5.5-java17-python3

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/app \
    PATH="/opt/venv/bin:$PATH"

USER root

WORKDIR $APP_HOME

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p $APP_HOME/feature_repo/data/input \
    && mkdir -p $APP_HOME/feature_repo/data/output \
    && chown -R spark:spark $APP_HOME/feature_repo

COPY requirements-linux.txt .

RUN python3 -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && /opt/venv/bin/pip install -r requirements-linux.txt \
    && rm requirements-linux.txt

RUN chmod -R 777 $APP_HOME/feature_repo

USER spark

COPY feature_repo/repo_definition.py $APP_HOME/feature_repo/
COPY feature_repo/feature_store.yaml $APP_HOME/feature_repo/
COPY feast_feature_engineering.py $APP_HOME

WORKDIR $APP_HOME/feature_repo

CMD ["sh", "-c", "python /app/feast_feature_engineering.py --feature-repo-path=/app/feature_repo"]
