# podman run -v ./feature_repo/data:/app/feature_repo/data quay.io/hbelmiro/fraud-detection-e2e-demo-feast:latest

FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/app \
    PATH="/opt/venv/bin:$PATH"

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN python3 -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && /opt/venv/bin/pip install -r requirements.txt \
    && rm requirements.txt

COPY feature_repo/repo_definition.py $APP_HOME/feature_repo/
COPY feature_repo/feature_store.yaml $APP_HOME/feature_repo/

COPY feast_apply.py $APP_HOME

WORKDIR $APP_HOME/feature_repo

ENV MINIO_ENDPOINT="http://minio-service:9000" \
    MINIO_ACCESS_KEY="minio" \
    MINIO_SECRET_KEY="minio123" \
    MINIO_BUCKET="mlpipeline" \
    FEATURE_REPO_REMOTE_DIR="artifacts/feature_repo"

CMD ["sh", "-c", "python feast_apply.py --feature-repo-path=$APP_HOME/feature_repo"]
