apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kserve-inferenceservice-manager-binding
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserve-inferenceservice-manager
subjects:
- kind: ServiceAccount
  name: pipeline-runner
  namespace: kubeflow