FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/app \
    PATH="/opt/venv/bin:$PATH"

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN python3 -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && /opt/venv/bin/pip install -r requirements.txt \
    && rm requirements.txt

ENV MINIO_ENDPOINT="http://minio-service:9000" \
    MINIO_ACCESS_KEY="minio" \
    MINIO_SECRET_KEY="minio123" \
    MINIO_BUCKET="mlpipeline" \
    REMOTE_FEATURE_REPO_DIR="artifacts/feature_repo"