FROM spark:3.5.5-scala2.12-java17-python3-ubuntu

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/app \
    PATH="/opt/venv/bin:$PATH"

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-linux.txt .

RUN python3 -m venv /opt/venv \
    && pip install --upgrade pip \
    && pip install -r requirements-linux.txt \
    && rm requirements-linux.txt

COPY train.py $APP_HOME/train.py

RUN mkdir $APP_HOME/features \
    && chown -R spark:spark $APP_HOME

USER spark

WORKDIR $APP_HOME

