FROM spark:3.5.4-scala2.12-java17-python3-ubuntu

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/app \
    PATH="/opt/venv/bin:$PATH" \
    MINIO_ENDPOINT="http://minio-service:9000" \
    MINIO_ACCESS_KEY="minio" \
    MINIO_SECRET_KEY="minio123" \
    MINIO_BUCKET="mlpipeline" \
    FEATURE_REPO_REMOTE_DIR="artifacts/feature_repo"

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-linux.txt .

RUN python3 -m venv /opt/venv \
    && pip install --upgrade pip \
    && pip install -r requirements-linux.txt \
    && rm requirements-linux.txt

COPY train.py $APP_HOME/train.py

RUN mkdir $APP_HOME/features \
    && chown -R spark:spark $APP_HOME

USER spark

WORKDIR $APP_HOME

