FROM registry.access.redhat.com/ubi9/python-311

WORKDIR /app

COPY requirements-linux.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements-linux.txt

COPY predictor.py .

USER root
RUN chown -R 1001:0 /app && \
    chmod -R 775 /app

USER default
