apiVersion: v1
kind: Secret
metadata:
  name: spark-config
  namespace: fraud-detection
stringData:
  spark: |
    spark_conf:
      spark.master: "local[*]"
      spark.ui.enabled: "false"
      spark.eventLog.enabled: "false"
      spark.sql.catalogImplementation: "hive"
      spark.sql.parser.quotedRegexColumnNames: "true"
      spark.sql.session.timeZone: "UTC"
      spark.sql.execution.arrow.fallback.enabled: "true"
      spark.sql.execution.arrow.pyspark.enabled: "true"