apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    # Enable mysql_native_password authentication
    default_authentication_plugin=mysql_native_password
    
    # Basic MySQL configuration
    innodb_buffer_pool_size=256M
    max_connections=200
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    
    # Logging
    log-error=/var/log/mysql/error.log
    slow_query_log=1
    slow_query_log_file=/var/log/mysql/slow.log
    long_query_time=2
    
    # Security
    skip-name-resolve
    bind-address=0.0.0.0
    
    [mysql]
    default-character-set=utf8mb4
    
    [client]
    default-character-set=utf8mb4 