name: Check uv.lock sync - pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/uv-lock-check-rest-predictor.yaml'
      - 'rest_predictor/pyproject.toml'
      - 'rest_predictor/uv.lock'
      - 'rest_predictor/requirements-linux.txt'
jobs:
  uv-lock-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check uv.lock is in sync with pyproject.toml
        uses: hbelmiro/uv-lock-check@v0.2.0
        with:
          pyproject-path: 'rest_predictor/pyproject.toml'

  requirements-txt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check requirements.txt is in sync with pyproject.toml
        uses: hbelmiro/uv-lock-check@v0.2.0
        with:
          pyproject-path: 'rest_predictor/pyproject.toml'
          command: 'uv pip compile --python-platform=linux pyproject.toml -o requirements-linux.txt'
          requirements-path: 'rest_predictor/requirements.linux.txt'
