name: KFP Pipelines Validated

on:
  push:
    branches: [ openshift ]

  pull_request:
    paths:
      - '**/*.py'
      - '**/*.yaml'
      - '**/*.yml'
      - '.github/workflows/validate-kfp-compiled-files.yaml'

jobs:
  check-pipelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check pipelines
        uses: hbelmiro/validate-kfp-compiled-files@ad586d760da7922fde248c870f985eba21891130
        with:
          pipelines-map-file: './.github/workflows/pipelines.json'
          requirements-file: './pipeline/requirements-linux.txt'
          extra-compile-args: '--disable-execution-caching-by-default'
