name: KFP Pipelines Validated

on:
  push:
    branches: [ main, rhoai, kubeflow ]

  pull_request:
    paths:
      - '**/*.py'
      - '**/*.yaml'
      - '**/*.yml'
      - '.github/workflows/validate-kfp-compiled-files.yaml'

jobs:
  check-pipelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'

      - name: Check pipelines
        uses: hbelmiro/validate-kfp-compiled-files@6c3966ea26d9c7c8b580d5cb3545b43851c5f271 # v0.2.0
        with:
          pipelines-map-file: './.github/workflows/pipelines.json'
          requirements-file: './pipeline/requirements-linux.txt'
          compile-args: '--disable-execution-caching-by-default'
